apiVersion: v1
description: Installs BIGBROTHER-agent in kubernetes
home: https://github.com/cyber-dev-skalovsi/big-brother/tree/main/supplemental/helm/BIGBROTHER-agent
name: BIGBROTHER-agent
appVersion: "0.3.0"
# Bump this version when publishing chart changes.
version: 0.1.5
sources:
  - https://github.com/cyber-dev-skalovsi/big-brother/tree/main/supplemental/helm/BIGBROTHER-agent
  - https://www.github.com/cyber-dev-skalovsi/big-brother/
  - https://github.com/cyber-dev-skalovsi/big-brother
icon: https://repository-images.githubusercontent.com/825470378/2710c6db-f934-4a8b-a2c4-7a0abbcd2ad6
maintainers:
  - name: cyber-dev-skalovsi
    email: 172505522+cyber-dev-skalovsi@users.noreply.github.com
