version: 2

project_name: BIGBROTHER

before:
  hooks:
    - go mod tidy
    - go generate -run fetchsmartctl ./agent

builds:
  - id: BIGBROTHER
    binary: BIGBROTHER
    main: internal/cmd/hub/hub.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: arm
      - goos: darwin
        goarch: arm

  - id: BIGBROTHER-agent
    binary: BIGBROTHER-agent
    main: internal/cmd/agent/agent.go
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/cyber-dev-skalovsi/big-brother/internal/ghupdate.buildGOARM={{ .Arm }}
    goos:
      - linux
      - darwin
      - freebsd
      - openbsd
      - windows
    goarch:
      - amd64
      - arm64
      - arm
      - mips64
      - riscv64
      - mipsle
      - mips
      - ppc64le
    goarm:
      - "5"
      - "6"
      - "7"
    gomips:
      - hardfloat
      - softfloat
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: linux
        goarch: mips64
        gomips: softfloat
      - goos: linux
        goarch: mipsle
        gomips: hardfloat
      - goos: linux
        goarch: mips
        gomips: hardfloat
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: riscv64

  - id: BIGBROTHER-agent-linux-amd64-glibc
    binary: BIGBROTHER-agent
    main: internal/cmd/agent/agent.go
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=glibc
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: BIGBROTHER-agent
    formats: [tar.gz]
    ids:
      - BIGBROTHER-agent
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}
      {{- if ne .Arm "6" }}{{ with .Arm }}v{{ . }}{{ end }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

  - id: BIGBROTHER-agent-linux-amd64-glibc
    formats: [tar.gz]
    ids:
      - BIGBROTHER-agent-linux-amd64-glibc
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}_glibc

  - id: BIGBROTHER
    formats: [tar.gz]
    ids:
      - BIGBROTHER
    name_template: >-
      {{ .Binary }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        formats: [zip]

nfpms:
  - id: BIGBROTHER-agent
    package_name: BIGBROTHER-agent
    description: |-
      Agent for BIGBROTHER
      BIGBROTHER is a lightweight server monitoring platform that includes Docker
      statistics, historical data, and alert functions. It has a friendly web
      interface, simple configuration, and is ready to use out of the box.
      It supports automatic backup, multi-user, OAuth authentication, and
      API access.
    maintainer: cyber-dev-skalovsi <172505522+cyber-dev-skalovsi@users.noreply.github.com>
    section: net
    ids:
      - BIGBROTHER-agent
    formats:
      - deb
    contents:
      - src: ./supplemental/debian/BIGBROTHER-agent.service
        dst: lib/systemd/system/BIGBROTHER-agent.service
        packager: deb
      - src: ./supplemental/debian/copyright
        dst: usr/share/doc/BIGBROTHER-agent/copyright
        packager: deb
      - src: ./supplemental/debian/lintian-overrides
        dst: usr/share/lintian/overrides/BIGBROTHER-agent
        packager: deb
    scripts:
      postinstall: ./supplemental/debian/postinstall.sh
      preremove: ./supplemental/debian/prerm.sh
      postremove: ./supplemental/debian/postrm.sh
    deb:
      predepends:
        - adduser
        - debconf
      scripts:
        templates: ./supplemental/debian/templates
        config: ./supplemental/debian/config.sh

scoops:
  - ids: [BIGBROTHER-agent]
    name: BIGBROTHER-agent
    repository:
      owner: cyber-dev-skalovsi
      name: big-brother-scoops
    homepage: "https://github.com/cyber-dev-skalovsi/big-brother"
    description: "Agent for BIGBROTHER, a lightweight server monitoring platform."
    license: MIT
    skip_upload: '{{ if eq (tolower .Env.IS_FORK) "true" }}true{{ else }}auto{{ end }}'

# # Needs choco installed, so doesn't build on linux / default gh workflow :(
# chocolateys:
#   - title: BIGBROTHER Agent
#     ids: [BIGBROTHER-agent]
#     package_source_url: https://github.com/cyber-dev-skalovsi/big-brother-chocolatey
#     owners: cyber-dev-skalovsi
#     authors: cyber-dev-skalovsi
#     summary: 'Agent for BIGBROTHER, a lightweight server monitoring platform.'
#     description: |
#       BIGBROTHER is a lightweight server monitoring platform that includes Docker statistics, historical data, and alert functions.

#       It has a friendly web interface, simple configuration, and is ready to use out of the box. It supports automatic backup, multi-user, OAuth authentication, and API access.
#     license_url: https://github.com/cyber-dev-skalovsi/big-brother/blob/main/LICENSE
#     project_url: https://github.com/cyber-dev-skalovsi/big-brother
#     project_source_url: https://github.com/cyber-dev-skalovsi/big-brother
#     docs_url: https://github.com/cyber-dev-skalovsi/big-brother/guide/getting-started
#     icon_url: https://cdn.jsdelivr.net/gh/selfhst/icons/png/BIGBROTHER.png
#     bug_tracker_url: https://github.com/cyber-dev-skalovsi/big-brother/issues
#     copyright: 2025 cyber-dev-skalovsi
#     tags: foss cross-platform admin monitoring
#     require_license_acceptance: false
#     release_notes: 'https://github.com/cyber-dev-skalovsi/big-brother/releases/tag/v{{ .Version }}'

brews:
  - ids: [BIGBROTHER-agent]
    name: BIGBROTHER-agent
    repository:
      owner: cyber-dev-skalovsi
      name: homebrew-big-brother
    homepage: "https://github.com/cyber-dev-skalovsi/big-brother"
    description: "Agent for BIGBROTHER, a lightweight server monitoring platform."
    license: MIT
    skip_upload: '{{ if eq (tolower .Env.IS_FORK) "true" }}true{{ else }}auto{{ end }}'
    extra_install: |
      (bin/"BIGBROTHER-agent-launcher").write <<~EOS
        #!/bin/bash
        set -a
        if [ -f "$HOME/.config/BIGBROTHER/BIGBROTHER-agent.env" ]; then
          source "$HOME/.config/BIGBROTHER/BIGBROTHER-agent.env"
        fi
        set +a
        exec #{bin}/BIGBROTHER-agent "$@"
      EOS
      (bin/"BIGBROTHER-agent-launcher").chmod 0755
    service: |
      run ["#{bin}/BIGBROTHER-agent-launcher"]
      log_path "#{Dir.home}/.cache/BIGBROTHER/BIGBROTHER-agent.log"
      error_log_path "#{Dir.home}/.cache/BIGBROTHER/BIGBROTHER-agent.log"
      keep_alive true
      restart_delay 5
      process_type :background

winget:
  - ids: [BIGBROTHER-agent]
    name: BIGBROTHER-agent
    package_identifier: cyber-dev-skalovsi.BIGBROTHER-agent
    publisher: cyber-dev-skalovsi
    license: MIT
    license_url: "https://github.com/cyber-dev-skalovsi/big-brother/blob/main/LICENSE"
    copyright: "2025 cyber-dev-skalovsi"
    homepage: "https://github.com/cyber-dev-skalovsi/big-brother"
    release_notes_url: "https://github.com/cyber-dev-skalovsi/big-brother/releases/tag/v{{ .Version }}"
    publisher_support_url: "https://github.com/cyber-dev-skalovsi/big-brother/issues"
    short_description: "Agent for BIGBROTHER, a lightweight server monitoring platform."
    skip_upload: '{{ if eq (tolower .Env.IS_FORK) "true" }}true{{ else }}auto{{ end }}'
    description: |
      BIGBROTHER is a lightweight server monitoring platform that includes Docker
      statistics, historical data, and alert functions. It has a friendly web
      interface, simple configuration, and is ready to use out of the box.
      It supports automatic backup, multi-user, OAuth authentication, and
      API access.
    tags:
      - homelab
      - monitoring
      - self-hosted
    repository:
      owner: cyber-dev-skalovsi
      name: big-brother-winget
      branch: cyber-dev-skalovsi.BIGBROTHER-agent-{{ .Version }}
      token: "{{ .Env.WINGET_TOKEN }}"
      # pull_request:
      #   enabled: true
      #   draft: false
      #   base:
      #     owner: microsoft
      #     name: winget-pkgs
      #     branch: master

release:
  draft: true

changelog:
  disable: true
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
