blank_issues_enabled: false
contact_links:
  - name: 🗣️ Translations
    url: https://crowdin.com/project/BIGBROTHER
    about: Please report translation issues and request new translations here. 
  - name: 💬 Support and questions
    url: https://github.com/cyber-dev-skalovsi/big-brother/discussions
    about: Ask and answer questions here.
  - name: ℹ️ View the Common Issues page
    url: https://github.com/cyber-dev-skalovsi/big-brother/guide/common-issues
    about: Find information about commonly encountered problems.
