FROM --platform=$BUILDPLATFORM golang:alpine AS builder

WORKDIR /app

# Download Go modules
COPY ../go.mod ../go.sum ./
RUN go mod download

# Copy source files
COPY . ./

RUN apk add --no-cache \
    unzip \
    ca-certificates

RUN update-ca-certificates

# Build
ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOGC=75 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -ldflags "-w -s" -o /bigbrother ./internal/cmd/hub

# ? -------------------------
FROM scratch

COPY --from=builder /bigbrother /
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Ensure data persistence across container recreations
VOLUME ["/bigbrother_data"]

EXPOSE 8090

ENTRYPOINT [ "/bigbrother" ]
CMD ["serve", "--http=0.0.0.0:8090"]